language: minimal

services:
  - docker

cache:
  directories:
    - .build

before_script:
  - rmdir --ignore-fail-on-non-empty .build

script:
  - make all GO_TEST_FLAGS='-race -coverprofile=coverage.txt' USE_DOCKER=1 COMPOSE_FILE=docker-compose.override.yml
  - git diff --exit-code

after_success:
  - bash <(curl -s https://codecov.io/bash)
